<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_m_sqlRsWebPartctl00ctl19_1</name>
   <tag></tag>
   <elementGuidId>498840de-c37f-4e6d-80de-572883b989cc</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m_sqlRsWebPart_ctl00_ctl19_ctl06_ctl05_divDropDown_ctl03</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>m_sqlRsWebPart$ctl00$ctl19$ctl06$ctl05$divDropDown$ctl03</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$get('m_sqlRsWebPart_ctl00_ctl19_ctl06_ctl05').control.OnValidValueClick(this, 'm_sqlRsWebPart_ctl00_ctl19_ctl06_ctl05_divDropDown_ctl00');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m_sqlRsWebPart_ctl00_ctl19_ctl06_ctl05_divDropDown_ctl03&quot;)</value>
   </webElementProperties>
</WebElementEntity>
