<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Export</name>
   <tag></tag>
   <elementGuidId>3a1c4704-30ed-4f70-9bbb-62cebfe3fe49</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mp1_0_2_Anchor&quot;)/span[@id=&quot;m_sqlRsWebPart_RSWebPartToolbar_ctl00_RptControls_RSActionMenu_Export&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
