<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Scope Survival Fleet Trend</name>
   <tag></tag>
   <elementGuidId>fd56cf31-482f-49b0-bc73-ebe4803887f7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/sites/CASSI_Online/_layouts/ReportServer/RSViewerPage.aspx?rv:RelativeReportUrl=/sites/CASSI_Online/Reports/Scope%20Survival%20Fleet%20Trend.rdl&amp;rv:HeaderArea=none</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Scope Survival Fleet Trend</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-2&quot;)/table[@class=&quot;fixed&quot;]/tbody[1]/tr[2]/td[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
