<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>_Dashboards</name>
   <tag></tag>
   <elementGuidId>7431bfc6-e961-4caf-ac03-2feffcf16554</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value></value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboards</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-1&quot;)/table[@class=&quot;fixed&quot;]/tbody[1]/tr[2]/td[1]/table[@class=&quot;fixed&quot;]/tbody[1]/tr[2]/h3[1]/[1]</value>
   </webElementProperties>
</WebElementEntity>
