<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Overview Dashboard</name>
   <tag></tag>
   <elementGuidId>32450986-dc73-443a-9ea9-30521e2f41b7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/sites/CASSI_Online/_layouts/ReportServer/RSViewerPage.aspx?rv:RelativeReportUrl=/sites/CASSI_Online/Reports/Overview%20Dashboard.rdl&amp;rv:HeaderArea=none</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Overview Dashboard</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-1&quot;)/table[@class=&quot;fixed&quot;]/tbody[1]/tr[2]/td[1]/table[@class=&quot;fixed&quot;]/tbody[1]/tr[4]/[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
